{
 "title": "Octoprint",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Done",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "octoprint_done_prints_total" }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "octoprint_cancelled_prints_total"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "octoprint_failed_prints_total" }
   ]
  },
  {
   "title": "Printer Cam",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "content": "<img id=\"webcam_image\" data-bind=\"css: { flipH: settings.webcam_flipH(), flipV: settings.webcam_flipV() }, event: { load: onWebcamLoaded, error: onWebcamErrored }, visible: !webcamError()\" src=\"http://192.168.0.24:8080/?action=stream\">\n\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPi Core Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "octoprint_raspberry_core_temperature"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "format": "rpi",
   "valueName": "current",
   "targets": [
    { "expr": "octoprint_print_fan_speed" }
   ]
  },
  {
   "title": "Electricity total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 0.82" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spool tracker",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS \"time\",\n  name AS metric,\n  used AS \"used\",\n  weight AS \"weight\",\n  cost AS \"cost\"\nFROM spools\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Client Number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "octoprint_client_num", "legendFormat": "Clients" }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Hotend Temperature ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "octoprint_temperatures_actual{identifier=\"T0\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "octoprint_temperatures_target{identifier=\"T0\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Bed Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "octoprint_temperatures_actual{identifier=\"B\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "octoprint_temperatures_target{identifier=\"B\"}",
     "legendFormat": "Target"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Realtime current [A]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Octoprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "A",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Realtime Power [W]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Octoprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Realtime voltage [V] ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Octoprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "V",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Realtime total [Wh]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Octoprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Print statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Print status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "octoprint_print_progress", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Prints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "octoprint_cancelled_prints_total",
     "legendFormat": "Cancelled"
    },
    { "expr": "octoprint_done_prints_total", "legendFormat": "Done" },
    { "expr": "octoprint_failed_prints_total", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Movement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "octoprint_movement", "legendFormat": "{{identifier}}" }
   ]
  }
 ]
}